"""
resize.py

Module to resize an image to a given width and/or height.

You can pass both width and height, or just one of them. If only one
is provided, the other is calculated automatically to keep the
image's original aspect ratio.

Usage as a module (from another script):

    from resize import resize_image

    # Both dimensions given (stretches to exactly 1080x1080)
    path = resize_image(
        image_path="test/image/bg.jpg",
        width=1080,
        height=1080,
    )
    print(path)

    # Only width given: height is calculated to keep the aspect ratio
    path = resize_image(
        image_path="test/image/bg.jpg",
        width=1080,
    )

    # Only height given: width is calculated to keep the aspect ratio
    path = resize_image(
        image_path="test/image/bg.jpg",
        height=1080,
    )

    # Or if you want the Image object back instead of saving to disk:
    img = resize_image(
        image_path="test/image/bg.jpg",
        width=1080,
        height=1080,
        return_type="image",
    )
    img.show()

Requirements:
    pip install Pillow
"""

from pathlib import Path
from typing import Literal, Union
from PIL import Image
from file_util import save_file

# Carpeta donde vive este archivo (resize.py).
# Se usa como base para resolver rutas relativas, sin importar desde
# dónde se ejecute el script o desde qué módulo se importe.
BASE_DIR = Path(__file__).resolve().parent


ImageInput = Union[str, Path, Image.Image]


def _resolve_path(path: Union[str, Path]) -> Path:
    """
    Si `path` es absoluta, la devuelve tal cual.
    Si es relativa, la resuelve tomando como base la carpeta donde
    está resize.py (BASE_DIR), no el directorio de trabajo actual.
    """
    path = Path(path)
    if path.is_absolute():
        return path
    return (BASE_DIR / path).resolve()


def _load_image(image: ImageInput) -> Image.Image:
    """
    Acepta una ruta (str/Path) o un objeto Image ya cargado, y siempre
    devuelve un objeto Image en modo RGBA.
    """
    if isinstance(image, Image.Image):
        return image.convert("RGBA")
    path = _resolve_path(image)
    if not path.exists():
        raise FileNotFoundError(f"Image not found: {path}")
    return Image.open(path).convert("RGBA")


def resize_image(
    image_path: ImageInput,
    width: int = None,
    height: int = None,
    keep_aspect_ratio: bool = False,
    output_path: Union[str, Path] = None,
    return_type: Literal["path", "image"] = "path",
) -> Union[str, Image.Image]:
    """
    Resizes an image to the given (width, height).

    Args:
        image_path: image to resize. Path (str/Path, absolute or
                  relative to resize.py's folder) or an already-loaded
                  PIL.Image.
        width: final image width (px). Optional if height is given.
        height: final image height (px). Optional if width is given.
                  If only one of width/height is provided, the other
                  is calculated automatically to keep the image's
                  original aspect ratio. At least one of the two must
                  be provided.
        keep_aspect_ratio: only applies when BOTH width and height are
                  provided. If True, does not stretch the image: it
                  resizes it keeping the original aspect ratio to fit
                  within (width, height) and adds transparent letterbox
                  padding to complete the exact canvas. If False
                  (default), the image is stretched exactly to
                  (width, height).
        output_path: where to save the result. If not provided and
                  return_type="path", an automatic name is generated by
                  adding "_resize" to the original name.
        return_type: "path" -> saves the file and returns the path (str).
                  "image" -> returns the PIL.Image object without saving it
                  (unless output_path was also provided, in which case it
                  saves it anyway and also returns the image).

    Returns:
        str with the path to the generated file, or a PIL.Image object,
        depending on the `return_type` parameter.
    """
    if width is None and height is None:
        raise ValueError("You must provide at least width or height.")

    image = _load_image(image_path)

    # Si falta una de las dos dimensiones, se calcula manteniendo la
    # relación de aspecto original de la imagen.
    if width is None:
        ratio = height / image.height
        width = round(image.width * ratio)
    elif height is None:
        ratio = width / image.width
        height = round(image.height * ratio)

    if keep_aspect_ratio:
        # Redimensiona manteniendo proporción y centra sobre un lienzo
        # transparente del tamaño exacto pedido.
        fitted_image = image.copy()
        fitted_image.thumbnail((width, height), Image.LANCZOS)

        canvas = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        x = (width - fitted_image.width) // 2
        y = (height - fitted_image.height) // 2
        canvas.paste(fitted_image, (x, y), fitted_image)
        result = canvas
    else:
        result = image.resize((width, height), Image.LANCZOS)

    if return_type == "image":
        if output_path:
            save_file(result.convert("RGB"), output_path)
        return result

    # return_type == "path"
    if output_path is None:
        if isinstance(image_path, Image.Image):
            output_path = BASE_DIR / "resize.png"
        else:
            source_path = _resolve_path(image_path)
            output_path = source_path.parent / f"{source_path.stem}_resize{source_path.suffix}"
    else:
        output_path = _resolve_path(output_path)

    return save_file(result.convert("RGB"), output_path)


if __name__ == "__main__":
    # Ejemplo de uso por línea de comandos
    import argparse

    parser = argparse.ArgumentParser(description="Resizes an image to a given width and height.")
    parser.add_argument("image", help="Path to the image to resize")
    parser.add_argument("--width", type=int, default=None, help="Final width (optional if --height is given)")
    parser.add_argument("--height", type=int, default=None, help="Final height (optional if --width is given)")
    parser.add_argument("--keep-aspect-ratio", action="store_true", help="Do not stretch the image, keep its aspect ratio")
    parser.add_argument("--output", default=None, help="Output path (optional)")
    args = parser.parse_args()

    final_path = resize_image(
        image_path=args.image,
        width=args.width,
        height=args.height,
        keep_aspect_ratio=args.keep_aspect_ratio,
        output_path=args.output,
    )
    print(f"Image generated at: {final_path}")